export const ERRORS = {
    INPUT_NOT_OBJECT: "Input must be an object",
    CHAT_ID_STRING: "'chatID' must be a string",
    REPLY_TO_STRING: "'replyTo' must be a string if provided",
    BODY_NOT_OBJECT: "'body' must be an object",
    BODY_TYPE_STRING: "'body.type' must be a string",
    BODY_TYPE_NOT_ALLOWED: "Not allowed 'body.type'",
    BODY_CONTENT_REQUIRED: "'body.content' must be provided",
    INVALID_BODY_CONTENT: "Invalid 'body.content' for the provided 'body.type'",
    SYSTEM_CHAT_ID_REQUIRED: "chatID is required when user message is not provided",
    NUMBER_NOT_INTEGER: "Invalid message body. It must be a valid integer.",
    OPTION_NOT_EXIST: "The provided option does not exist.",
    MIME_NOT_ALLOWED: "MIME type not allowed.",

    INVALID_BODY_TYPE_EXPECTED: (expected: string) => `Invalid body type. Expected ${expected}`,
    TEXT_TOO_SHORT: (min: number) => `The message body is too short. It must be at least ${min} characters long.`,
    TEXT_TOO_LONG: (max: number) => `The message body is too long. It should be no more than ${max} characters long.`,
    NUMBER_TOO_SMALL: (min: number) => `The number is too small. The minimum allowed value is ${min}.`,
    NUMBER_TOO_BIG: (max: number) => `The number is too big. The maximum allowed value is ${max}.`,
    DATE_TOO_OLD: (min: Date) => `The date is too old. The minimum allowed is ${min.toISOString()}.`,
    DATE_TOO_EARLY: (max: Date) => `The date is too early. The maximum allowed is ${max.toISOString()}.`,
    TOO_MANY_OPTIONS: (max: number) => `Too many options. The maximum allowed is ${max}.`,
    TOO_MANY_FILES: (max: number) => `Too many files. The maximum allowed is ${max}.`,
    FILE_TOO_LARGE: (maxMB: number) => `Too large file. The maximum allowed size is ${maxMB} MB.`,
};
